### ISSUE TITLE
Cannot add plugin with the usual method as described

### ISSUE THREAD

**Issue by tokou** [Polidea/gradle-config#4]
The plugin is not found on https://plugins.gradle.org/m2/
The method described in the README does not work
```
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "com.polidea:gradle-config:1.0.0"
  }
}
```

The new method works though 
```
plugins {
  id "com.polidea.android.config" version "1.0.0"
}
```

When you go to the polidea folder in the repository https://repo.jfrog.org/artifactory/libs-release-bintray/com/polidea/ you cannot find a `gradle-config` directory

**Comment by pawelByszewski** [comment]
Although the sample was updated
https://github.com/Polidea/gradle-config/blob/master/sample_app/app/build.gradle
the readme described old config. 
In the old fashion way declaring dependency should look like this 
`classpath "com.polidea.android:config:1.0.0"`
Please check out the updated readme.
